### ISSUE TITLE
Docker version detection seems to be wrong on Ubuntu 16.04

### ISSUE THREAD

**Issue by miloskroulik** [mortenson/drupal-docker-lite#1]
When I execute `./start.sh`, I get message `Please upgrade Docker to version 17.05 or later and try running the script again`. However, my version of docker seems to be sufficient, because running `docker --version` returns `Docker version 17.05.0-ce, build 89658be`. In the script variable `${DOCKER_VERSION[0]}` returns just `17`.

BTW. I'm using official repository from Docker (`deb https://apt.dockerproject.org/repo ubuntu-xenial main`). Drupal seems to be installed fine.

**Comment by mortenson** [comment]
@miloskroulik It looks like I was checking for versions less than 17.06 in the script, I'm not sure why. I updated the check here https://github.com/mortenson/drupal-docker-lite/commit/0adbdfd6bb29b62544e869ab6d878b0b40114a2e

Could you pull master and try running the script again?

**Comment by mortenson** [comment]
I'm closing this out as I haven't heard anything in awhile - feel free to open a new issue if you're still having a problem.
