### ISSUE TITLE
start.sh should only allow profile installation for profiles that actually exist

### ISSUE THREAD

**Issue by mortenson** [mortenson/drupal-docker-lite#16]
When `ddl.sh start` prompts you to install a profile, you can enter anything you want. We should, _somehow_, only allow profiles that exist, or better yet list profiles and allow the user to choose numerically instead of typing the full name.

**Comment by mattgrill** [comment]
👍  This would be super helpful.

**Comment by mortenson** [comment]
Done! We now present a select list, with the added UX of also allowing users to type the name of the profile if it's in the list. So when presented with:
```
$ ddl start
drupalddl_mailhog_1 is up-to-date
drupalddl_mysql_1 is up-to-date
drupalddl_php_1 is up-to-date
Drupal does not appear to be installed yet
Do you want to install a site profile? [y/n] y
Which profile would you like to install?
1) minimal
2) standard
Selection: 
```
You can type 1, 2, minimal, or standard. Bash-fu! Please re-open if you run into any quirks.
