### ISSUE TITLE
Functional tests are not working

### ISSUE THREAD

**Issue by chrfritsch** [mortenson/drupal-docker-lite#8]
Running `./ddl.sh exec ./docroot/vendor/bin/phpunit -c ./docroot/core ./docroot/core/tests/Drupal/KernelTests/Core/Form/FormCacheTest.php` works fine.

But for example running `./ddl.sh exec ./docroot/vendor/bin/phpunit -c ./docroot/core ./docroot/core/modules/media/tests/src/Functional/MediaAccessTest.php`

throws issues like:
1) Drupal\Tests\media\Functional\MediaAccessTest::testMediaAccess
Behat\Mink\Exception\ElementNotFoundException: Button with id|name|label|value "Log in" not found.

/var/www/html/docroot/core/tests/Drupal/Tests/WebAssert.php:76
/var/www/html/docroot/core/tests/Drupal/Tests/BrowserTestBase.php:816
/var/www/html/docroot/core/tests/Drupal/Tests/BrowserTestBase.php:753
/var/www/html/docroot/core/modules/media/tests/src/Functional/MediaFunctionalTestTrait.php:69
/var/www/html/docroot/core/modules/media/tests/src/Functional/MediaUiFunctionalTest.php:28

**Comment by mortenson** [comment]
@chrfritsch This test passes for me with Drupal core 8.5.x, if you're running on an old/existing drupal-docker-lite checkout, could you run `git pull && ./ddl.sh rebuild` then try the test again?

If it's still failing, please let me know.

**Comment by chrfritsch** [comment]
Damn it, i tried it on my working machine and there it works.

I think there must be something wrong on my private machine. But i have no freaking idea what....
